# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 693)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/transparent/ICRAF.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 600))
        self.frame.setStyleSheet(_fromUtf8("border-image: url(:/background/IMG_7136(s).jpg);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.textEdit = QtGui.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(550, 0, 231, 181))
        self.textEdit.setStyleSheet(_fromUtf8("border-image: url(:/background/text_background.jpg);"))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuInput = QtGui.QMenu(self.menuBar)
        self.menuInput.setObjectName(_fromUtf8("menuInput"))
        self.menuSimulation = QtGui.QMenu(self.menuBar)
        self.menuSimulation.setObjectName(_fromUtf8("menuSimulation"))
        self.menuResult = QtGui.QMenu(self.menuBar)
        self.menuResult.setObjectName(_fromUtf8("menuResult"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuLanguages = QtGui.QMenu(self.menuBar)
        self.menuLanguages.setObjectName(_fromUtf8("menuLanguages"))
        self.menuProject = QtGui.QMenu(self.menuBar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menuBar)
        self.action_Maps = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/map.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/global.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Maps.setIcon(icon1)
        self.action_Maps.setObjectName(_fromUtf8("action_Maps"))
        self.action_Biophysics = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/transparent/environment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/environment.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Biophysics.setIcon(icon2)
        self.action_Biophysics.setObjectName(_fromUtf8("action_Biophysics"))
        self.action_Economy = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/economy.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/dollar.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Economy.setIcon(icon3)
        self.action_Economy.setObjectName(_fromUtf8("action_Economy"))
        self.action_Social = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/community.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../Resources/icon/transparent/comunitiy.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Social.setIcon(icon4)
        self.action_Social.setObjectName(_fromUtf8("action_Social"))
        self.action_Input_Timeseries = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/timeseries.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Input_Timeseries.setIcon(icon5)
        self.action_Input_Timeseries.setObjectName(_fromUtf8("action_Input_Timeseries"))
        self.action_Play = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/transparent/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Play.setIcon(icon6)
        self.action_Play.setObjectName(_fromUtf8("action_Play"))
        self.action_Pause = QtGui.QAction(MainWindow)
        self.action_Pause.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Pause.setIcon(icon7)
        self.action_Pause.setObjectName(_fromUtf8("action_Pause"))
        self.action_Stop = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../Resources/icon/transparent/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Stop.setIcon(icon8)
        self.action_Stop.setObjectName(_fromUtf8("action_Stop"))
        self.action_Result = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/output.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/Result.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Result.setIcon(icon9)
        self.action_Result.setObjectName(_fromUtf8("action_Result"))
        self.action_Other = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/MainWindowIcons/icon/transparent/more.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.action_Other.setIcon(icon10)
        self.action_Other.setObjectName(_fromUtf8("action_Other"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionVietnamese = QtGui.QAction(MainWindow)
        self.actionVietnamese.setObjectName(_fromUtf8("actionVietnamese"))
        self.actionOpen_project = QtGui.QAction(MainWindow)
        self.actionOpen_project.setObjectName(_fromUtf8("actionOpen_project"))
        self.actionCreate_new_project = QtGui.QAction(MainWindow)
        self.actionCreate_new_project.setObjectName(_fromUtf8("actionCreate_new_project"))
        self.actionClone_project = QtGui.QAction(MainWindow)
        self.actionClone_project.setObjectName(_fromUtf8("actionClone_project"))
        self.actionLand_cover = QtGui.QAction(MainWindow)
        self.actionLand_cover.setObjectName(_fromUtf8("actionLand_cover"))
        self.toolBar.addAction(self.action_Maps)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Social)
        self.toolBar.addAction(self.action_Economy)
        self.toolBar.addAction(self.action_Biophysics)
        self.toolBar.addAction(self.action_Other)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Input_Timeseries)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Play)
        self.toolBar.addAction(self.action_Pause)
        self.toolBar.addAction(self.action_Stop)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Result)
        self.menuInput.addAction(self.action_Maps)
        self.menuInput.addAction(self.action_Input_Timeseries)
        self.menuSimulation.addAction(self.action_Play)
        self.menuSimulation.addAction(self.action_Pause)
        self.menuSimulation.addAction(self.action_Stop)
        self.menuResult.addAction(self.action_Result)
        self.menuHelp.addAction(self.actionHelp)
        self.menuLanguages.addAction(self.actionEnglish)
        self.menuLanguages.addAction(self.actionVietnamese)
        self.menuProject.addAction(self.actionOpen_project)
        self.menuProject.addAction(self.actionCreate_new_project)
        self.menuProject.addAction(self.actionClone_project)
        self.menuSettings.addAction(self.actionLand_cover)
        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuInput.menuAction())
        self.menuBar.addAction(self.menuSimulation.menuAction())
        self.menuBar.addAction(self.menuResult.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuBar.addAction(self.menuLanguages.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "FALLOW", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#00ff00;\">FALLOW</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FALLOW (Forest, Agroforest, Low-value Lands Or Waste?) model was designed (van Noordwijk, 2001) to simulate land-cover change at landscape level driven by stakeholder decisions on labour and land allocation, and its consequence to local people\'s income and carbon storage in the landscape.</span></p></body></html>", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.menuInput.setTitle(_translate("MainWindow", "Input", None))
        self.menuSimulation.setTitle(_translate("MainWindow", "Simulation", None))
        self.menuResult.setTitle(_translate("MainWindow", "Result", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuLanguages.setTitle(_translate("MainWindow", "Languages", None))
        self.menuProject.setTitle(_translate("MainWindow", "Project", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.action_Maps.setText(_translate("MainWindow", "&Maps", None))
        self.action_Maps.setToolTip(_translate("MainWindow", "Input Maps", None))
        self.action_Maps.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.action_Biophysics.setText(_translate("MainWindow", "&Biophysics", None))
        self.action_Biophysics.setToolTip(_translate("MainWindow", "Input Biophysics Parameters", None))
        self.action_Biophysics.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.action_Economy.setText(_translate("MainWindow", "&Economy", None))
        self.action_Economy.setToolTip(_translate("MainWindow", "Input Economy Parameters", None))
        self.action_Economy.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.action_Social.setText(_translate("MainWindow", "&Social", None))
        self.action_Social.setToolTip(_translate("MainWindow", "Input Social Parameters", None))
        self.action_Social.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_Input_Timeseries.setText(_translate("MainWindow", "&Timeseries", None))
        self.action_Input_Timeseries.setToolTip(_translate("MainWindow", "Input Timeseries", None))
        self.action_Input_Timeseries.setShortcut(_translate("MainWindow", "Ctrl+T", None))
        self.action_Play.setText(_translate("MainWindow", "P&lay", None))
        self.action_Play.setToolTip(_translate("MainWindow", "Play", None))
        self.action_Play.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.action_Pause.setText(_translate("MainWindow", "&Pause", None))
        self.action_Pause.setToolTip(_translate("MainWindow", "Pause", None))
        self.action_Pause.setShortcut(_translate("MainWindow", "Ctrl+P", None))
        self.action_Stop.setText(_translate("MainWindow", "&Stop", None))
        self.action_Stop.setToolTip(_translate("MainWindow", "Stop", None))
        self.action_Stop.setShortcut(_translate("MainWindow", "Ctrl+Space", None))
        self.action_Result.setText(_translate("MainWindow", "Result", None))
        self.action_Result.setToolTip(_translate("MainWindow", "Results", None))
        self.action_Result.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.action_Other.setText(_translate("MainWindow", "&Other", None))
        self.action_Other.setToolTip(_translate("MainWindow", "Input Other Parameters", None))
        self.action_Other.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "Ctrl+H", None))
        self.actionEnglish.setText(_translate("MainWindow", "English", None))
        self.actionVietnamese.setText(_translate("MainWindow", "Vietnamese", None))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project", None))
        self.actionCreate_new_project.setText(_translate("MainWindow", "Create new project", None))
        self.actionClone_project.setText(_translate("MainWindow", "Clone project", None))
        self.actionLand_cover.setText(_translate("MainWindow", "Land cover", None))

import background_rc
import icons_rc
