# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MapInputUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1551, 982)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MapInputWidget = QtWidgets.QWidget(self.centralwidget)
        self.MapInputWidget.setEnabled(True)
        self.MapInputWidget.setMinimumSize(QtCore.QSize(500, 500))
        self.MapInputWidget.setMouseTracking(True)
        self.MapInputWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.MapInputWidget.setAcceptDrops(True)
        self.MapInputWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MapInputWidget.setObjectName("MapInputWidget")
        self.gridLayout_2.addWidget(self.MapInputWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(386, 260))
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inputPixelSize = QtWidgets.QLineEdit(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPixelSize.sizePolicy().hasHeightForWidth())
        self.inputPixelSize.setSizePolicy(sizePolicy)
        self.inputPixelSize.setMinimumSize(QtCore.QSize(30, 20))
        self.inputPixelSize.setMaximumSize(QtCore.QSize(30, 20))
        self.inputPixelSize.setObjectName("inputPixelSize")
        self.horizontalLayout.addWidget(self.inputPixelSize)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.mapTree = QtWidgets.QTreeView(self.dockWidgetContents)
        self.mapTree.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapTree.sizePolicy().hasHeightForWidth())
        self.mapTree.setSizePolicy(sizePolicy)
        self.mapTree.setMinimumSize(QtCore.QSize(350, 0))
        self.mapTree.setMouseTracking(True)
        self.mapTree.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.mapTree.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.mapTree.setAcceptDrops(True)
        self.mapTree.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mapTree.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.mapTree.setProperty("showDropIndicator", False)
        self.mapTree.setDragEnabled(False)
        self.mapTree.setDragDropOverwriteMode(False)
        self.mapTree.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.mapTree.setTextElideMode(QtCore.Qt.ElideRight)
        self.mapTree.setObjectName("mapTree")
        self.gridLayout.addWidget(self.mapTree, 1, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.openMap = QtWidgets.QAction(MainWindow)
        self.openMap.setObjectName("openMap")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.action_Compare = QtWidgets.QAction(MainWindow)
        self.action_Compare.setObjectName("action_Compare")
        self.toolBar.addAction(self.openMap)
        self.toolBar.addAction(self.save)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Input Maps"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Map Input"))
        self.label.setText(_translate("MainWindow", "Pixel size (ha)"))
        self.inputPixelSize.setText(_translate("MainWindow", "30"))
        self.openMap.setText(_translate("MainWindow", "&Open"))
        self.openMap.setToolTip(_translate("MainWindow", "Choose a map file"))
        self.openMap.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.save.setText(_translate("MainWindow", "&Save"))
        self.save.setToolTip(_translate("MainWindow", "Save project"))
        self.save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Compare.setText(_translate("MainWindow", "&Compare"))
        self.action_Compare.setToolTip(_translate("MainWindow", "Choose files to compare with"))
        self.action_Compare.setShortcut(_translate("MainWindow", "Ctrl+C"))

